# Paths are relative to Rails.root.

defaults: &defaults
  tmp_dir: <%= File.join(Rails.root, 'tmp') %>
  pdf_dir: <%= File.join(Rails.root, 'pdfs') %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
